PACKETS_OBJECTS=Packet.o   \
                Partial.o  \
                Key.o      \
                User.o     \
                Tag0.o     \
                Tag1.o     \
                Tag2.o     \
                Tag3.o     \
                Tag4.o     \
                Tag5.o     \
                Tag6.o     \
                Tag7.o     \
                Tag8.o     \
                Tag9.o     \
                Tag10.o    \
                Tag11.o    \
                Tag12.o    \
                Tag13.o    \
                Tag14.o    \
                Tag17.o    \
                Tag18.o    \
                Tag19.o    \
                Tag60.o    \
                Tag61.o    \
                Tag62.o    \
                Tag63.o
