# Subpackets Makefile
CXX?=g++
LDFLAGS=
CXXFLAGS=-std=c++11 -Wall -c

debug: CXXFLAGS += -g
debug: all

all: subpacket.o Tag2Sub0.o Tag2Sub1.o Tag2Sub2.o Tag2Sub3.o Tag2Sub4.o Tag2Sub5.o Tag2Sub6.o Tag2Sub7.o Tag2Sub8.o Tag2Sub9.o Tag2Sub10.o Tag2Sub11.o Tag2Sub12.o Tag2Sub13.o Tag2Sub14.o Tag2Sub15.o Tag2Sub16.o Tag2Sub17.o Tag2Sub18.o Tag2Sub19.o Tag2Sub20.o Tag2Sub21.o Tag2Sub22.o Tag2Sub23.o Tag2Sub24.o Tag2Sub25.o Tag2Sub26.o Tag2Sub27.o Tag2Sub28.o Tag2Sub29.o Tag2Sub30.o Tag2Sub31.o Tag2Sub32.o Tag17Sub1.o

subpacket.o: subpacket.h subpacket.cpp ../common/includes.h ../consts.h ../pgptime.h
	$(CXX) $(CXXFLAGS) subpacket.cpp

Tag2Sub0.o: Tag2Sub0.h Tag2Sub0.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub0.cpp

Tag2Sub1.o: Tag2Sub1.h Tag2Sub1.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub1.cpp

Tag2Sub2.o: Tag2Sub2.h Tag2Sub2.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub2.cpp

Tag2Sub3.o: Tag2Sub3.h Tag2Sub3.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub3.cpp

Tag2Sub4.o: Tag2Sub4.h Tag2Sub4.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub4.cpp

Tag2Sub5.o: Tag2Sub5.h Tag2Sub5.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub5.cpp

Tag2Sub6.o: Tag2Sub6.h Tag2Sub6.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub6.cpp

Tag2Sub7.o: Tag2Sub7.h Tag2Sub7.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub7.cpp

Tag2Sub8.o: Tag2Sub8.h Tag2Sub8.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub8.cpp

Tag2Sub9.o: Tag2Sub9.h Tag2Sub9.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub9.cpp

Tag2Sub10.o: Tag2Sub10.h Tag2Sub10.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub10.cpp

Tag2Sub11.o: Tag2Sub11.h Tag2Sub11.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub11.cpp

Tag2Sub12.o: Tag2Sub12.h Tag2Sub12.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub12.cpp

Tag2Sub13.o: Tag2Sub13.h Tag2Sub13.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub13.cpp

Tag2Sub14.o: Tag2Sub14.h Tag2Sub14.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub14.cpp

Tag2Sub15.o: Tag2Sub15.h Tag2Sub15.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub15.cpp

Tag2Sub16.o: Tag2Sub16.h Tag2Sub16.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub16.cpp

Tag2Sub17.o: Tag2Sub17.h Tag2Sub17.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub17.cpp

Tag2Sub18.o: Tag2Sub18.h Tag2Sub18.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub18.cpp

Tag2Sub19.o: Tag2Sub19.h Tag2Sub19.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub19.cpp

Tag2Sub20.o: Tag2Sub20.h Tag2Sub20.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub20.cpp

Tag2Sub21.o: Tag2Sub21.h Tag2Sub21.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub21.cpp

Tag2Sub22.o: Tag2Sub22.h Tag2Sub22.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub22.cpp

Tag2Sub23.o: Tag2Sub23.h Tag2Sub23.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub23.cpp

Tag2Sub24.o: Tag2Sub24.h Tag2Sub24.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub24.cpp

Tag2Sub25.o: Tag2Sub25.h Tag2Sub25.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub25.cpp

Tag2Sub26.o: Tag2Sub26.h Tag2Sub26.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub26.cpp

Tag2Sub27.o: Tag2Sub27.h Tag2Sub27.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub27.cpp

Tag2Sub28.o: Tag2Sub28.h Tag2Sub28.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub28.cpp

Tag2Sub29.o: Tag2Sub29.h Tag2Sub29.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub29.cpp

Tag2Sub30.o: Tag2Sub30.h Tag2Sub30.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub30.cpp

Tag2Sub31.o: Tag2Sub31.h Tag2Sub31.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub31.cpp

Tag2Sub32.o: Tag2Sub32.h Tag2Sub32.cpp ../Packets/Tag2.h subpacket.h
	$(CXX) $(CXXFLAGS) Tag2Sub32.cpp

Tag17Sub1.o: Tag17Sub1.h Tag17Sub1.cpp subpacket.h
	$(CXX) $(CXXFLAGS) Tag17Sub1.cpp

clean:
	rm -f *.o
