SUBPACKETS_SOURCES=subpacket.cpp    \
                   Tag2Sub0.cpp     \
                   Tag2Sub1.cpp     \
                   Tag2Sub2.cpp     \
                   Tag2Sub3.cpp     \
                   Tag2Sub4.cpp     \
                   Tag2Sub5.cpp     \
                   Tag2Sub6.cpp     \
                   Tag2Sub7.cpp     \
                   Tag2Sub8.cpp     \
                   Tag2Sub9.cpp     \
                   Tag2Sub10.cpp    \
                   Tag2Sub11.cpp    \
                   Tag2Sub12.cpp    \
                   Tag2Sub13.cpp    \
                   Tag2Sub14.cpp    \
                   Tag2Sub15.cpp    \
                   Tag2Sub16.cpp    \
                   Tag2Sub17.cpp    \
                   Tag2Sub18.cpp    \
                   Tag2Sub19.cpp    \
                   Tag2Sub20.cpp    \
                   Tag2Sub21.cpp    \
                   Tag2Sub22.cpp    \
                   Tag2Sub23.cpp    \
                   Tag2Sub24.cpp    \
                   Tag2Sub25.cpp    \
                   Tag2Sub26.cpp    \
                   Tag2Sub27.cpp    \
                   Tag2Sub28.cpp    \
                   Tag2Sub29.cpp    \
                   Tag2Sub30.cpp    \
                   Tag2Sub31.cpp    \
                   Tag2Sub32.cpp    \
                   Tag17Sub1.cpp
